export interface Resource {
  id: string
  title: string
  description: string
  category: "big-tech" | "interviews" | "vibe-coding" | "ui-components" | "ai-tools" | "pitch-prep" | "backend-deploy" | "beginner-mindset"
  type: "Video" | "Podcast" | "Website" | "Tool" | "Guide"
  url: string
  youtubeId?: string
  youtubeEmbedUrl?: string
  imageUrl?: string
  tags: string[]
  featured?: boolean
  badge?: string
  authorOrSource?: string
}

export const CATEGORIES = [
  { id: "all", label: "All Resources", icon: "Sparkles" },
  { id: "big-tech", label: "Big Tech Guides & Frameworks", icon: "Building2" },
  { id: "interviews", label: "Case Studies & Winner Breakdowns", icon: "Trophy" },
  { id: "vibe-coding", label: "Speed Building & Vibe-Coding", icon: "Code2" },
  { id: "ui-components", label: "Speed-Building UI Libraries", icon: "Layout" },
  { id: "ai-tools", label: "AI Infrastructure & APIs", icon: "Cpu" },
  { id: "backend-deploy", label: "Backend & Databases", icon: "Zap" },
  { id: "pitch-prep", label: "Pitching & Judging Strategy", icon: "Presentation" },
  { id: "beginner-mindset", label: "Hackathon Mindset & Beginners", icon: "Compass" },
]

export const RESOURCES_DATA: Resource[] = [
  // --- 1. BIG TECH GUIDES & FRAMEWORKS ---
  {
    id: "github-hackathon-pack",
    title: "GitHub Hackathon Pack & Organizer Toolkit",
    description: "A complete repository outlining pre-event prep, project structuring, repository hygiene, open-source license selection, and secret/API-key management to prevent security flags during judging.",
    category: "big-tech",
    type: "Guide",
    url: "https://github.com/gunthercox/HackathonPack",
    tags: ["GitHub", "Repo Hygiene", "Secret Management", "Official"],
    featured: true,
    badge: "Official GitHub",
    authorOrSource: "GitHub Engineering",
  },
  {
    id: "github-campus-experts",
    title: "GitHub Campus Experts Community Resources",
    description: "Curated documentation covering developer tool access, hosting setup, student developer packs, and team collaboration workflows.",
    category: "big-tech",
    type: "Guide",
    url: "https://github.com/github/hackathons/blob/main/Resources.md",
    tags: ["GitHub", "Campus Experts", "Student Pack", "Workflows"],
    authorOrSource: "GitHub Campus Experts",
  },
  {
    id: "devpost-submission-guide",
    title: "Devpost Official Hackathon Submission & Demo Video Guide",
    description: "The official guide on how to structure a Devpost submission page, write an effective project summary, and film a 2-minute demo video that aligns with scoring criteria.",
    category: "big-tech",
    type: "Guide",
    url: "https://info.devpost.com/resources",
    tags: ["Devpost", "Submission Guide", "Demo Video", "Scoring"],
    featured: true,
    badge: "Official Devpost",
    authorOrSource: "Devpost Platform",
  },
  {
    id: "devpost-ai-playbook",
    title: "4 Ways to Use AI to Elevate Hackathon Submissions",
    description: "Devpost’s playbook for integrating LLMs and modern agent workflows into competitive projects without overloading your scope.",
    category: "big-tech",
    type: "Guide",
    url: "https://info.devpost.com/resources",
    tags: ["Devpost", "AI Integration", "Scope Control", "Playbook"],
    badge: "Devpost AI Playbook",
    authorOrSource: "Devpost Insights",
  },
  {
    id: "google-cloud-startup-hub",
    title: "Google Cloud Startup & AI Resource Hub",
    description: "Access Google’s reference architectures, Gemini API quickstarts, and pre-built AI agent templates (ADK) designed for rapid prototyping.",
    category: "big-tech",
    type: "Tool",
    url: "https://cloud.google.com/startup/resources",
    tags: ["Google Cloud", "Gemini API", "AI Templates", "Architectures"],
    featured: true,
    badge: "Google Cloud Official",
    authorOrSource: "Google Developer Relations",
  },
  {
    id: "google-ai-agent-adk",
    title: "Google AI Agent Development Kit (ADK)",
    description: "Quickstart code bases and SDKs for building autonomous agentic apps during time-constrained sprints.",
    category: "big-tech",
    type: "Tool",
    url: "https://cloud.google.com/startup",
    tags: ["Google AI", "Agent Kit", "Quickstarts", "SDKs"],
    authorOrSource: "Google Startups",
  },
  {
    id: "microsoft-what-the-hack",
    title: "Microsoft What The Hack Challenge Framework",
    description: "Microsoft’s open-source repository containing real-world architecture scenarios, challenge blueprints, and team execution strategies used in enterprise and student hackathons.",
    category: "big-tech",
    type: "Guide",
    url: "https://microsoft.github.io/WhatTheHack/",
    tags: ["Microsoft", "Azure", "Challenge Blueprints", "Open Source"],
    badge: "Microsoft Open Source",
    authorOrSource: "Microsoft Cloud Advocates",
  },

  // --- 2. CASE STUDIES & WINNER BREAKDOWNS (YOUTUBE VIDEOS) ---
  {
    id: "anthropic-non-dev-winner",
    title: "How a Solo Non-Dev Won Anthropic’s Global Hackathon",
    description: "Breakdown of how strategic context engineering and rapid execution with Cursor beat 13,000+ applicants to win Anthropic's Global Hackathon.",
    category: "interviews",
    type: "Video",
    url: "https://www.youtube.com/watch?v=Geld8RS8jXc",
    youtubeId: "Geld8RS8jXc",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/Geld8RS8jXc?autoplay=1",
    tags: ["Anthropic", "Cursor", "AI Agents", "Global Winner"],
    featured: true,
    badge: "Global Winner",
    authorOrSource: "AI Engineering Teardown",
  },
  {
    id: "anthropic-setup-breakdown",
    title: "Anthropic Hackathon Winner's Setup & Prompts Breakdown",
    description: "Explores the custom Claude agents, environment setup, and prompts used to build a fully functional AI product in under 8 hours.",
    category: "interviews",
    type: "Video",
    url: "https://www.youtube.com/watch?v=sLNlPQOtmFk",
    youtubeId: "sLNlPQOtmFk",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/sLNlPQOtmFk?autoplay=1",
    tags: ["Claude Code", "Agent Setup", "8-Hour Sprint", "Anthropic"],
    badge: "1st Place Setup",
    authorOrSource: "Dev Insights Podcast",
  },
  {
    id: "sih-winner-strategy",
    title: "SIH Grand Finale Winner Strategy & Journey",
    description: "Covers team formation, picking the right problem statement, handling live technical failures, and pitching strategies for national hackathons.",
    category: "interviews",
    type: "Video",
    url: "https://www.youtube.com/watch?v=otiu176jwIk",
    youtubeId: "otiu176jwIk",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/otiu176jwIk?autoplay=1",
    tags: ["SIH 2025", "Grand Finale", "Problem Selection", "Winner"],
    badge: "SIH Special",
    authorOrSource: "Smart India Hackathon Series",
  },
  {
    id: "sih-igdtuw-team",
    title: "Winning SIH Team Interview (IGDTUW Team)",
    description: "Breaks down time management during the 36-hour sprint, rapid prototype strategies, and must-have technical skills for judge rounds.",
    category: "interviews",
    type: "Video",
    url: "https://www.youtube.com/watch?v=R8pbKnNpZtI",
    youtubeId: "R8pbKnNpZtI",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/R8pbKnNpZtI?autoplay=1",
    tags: ["SIH IGDTUW", "36-Hour Sprint", "Women in Tech", "Winner"],
    badge: "SIH Winner",
    authorOrSource: "Tech Student Chronicles",
  },
  {
    id: "sih-roadmap-execution",
    title: "SIH Winner Strategy & Execution Roadmap",
    description: "Focused on product execution, choosing high-impact problem statements, and presentation execution under strict deadlines.",
    category: "interviews",
    type: "Video",
    url: "https://www.youtube.com/watch?v=CFAN_gvmt4I",
    youtubeId: "CFAN_gvmt4I",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/CFAN_gvmt4I?autoplay=1",
    tags: ["SIH Roadmap", "Execution", "Presentation", "Guide"],
    badge: "Masterclass",
    authorOrSource: "Coding & Hackathon Masters",
  },

  // --- 3. SPEED BUILDING & VIBE-CODING (YOUTUBE VIDEOS) ---
  {
    id: "cursor-ai-tutorial",
    title: "Cursor AI Tutorial — Personal Tips & Tricks for Hackathons",
    description: "A complete breakdown on setting up AI code editors to quickly generate full-stack applications, execute complex refactors, and ship working prototypes during short hackathon timeframes.",
    category: "vibe-coding",
    type: "Video",
    url: "https://www.youtube.com/watch?v=rwxRoYzwkyM",
    youtubeId: "rwxRoYzwkyM",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/rwxRoYzwkyM?autoplay=1",
    tags: ["Cursor AI", "Vibe Coding", "Speed Building", "Full-Stack"],
    badge: "Vibe Coding Masterclass",
    authorOrSource: "AI Code Mastery",
  },
  {
    id: "cursor-beautiful-websites",
    title: "3 Ways to Build ACTUALLY Beautiful Websites Using Cursor AI",
    description: "Focuses on rapidly linking UI component frameworks with modern AI tools to build high-converting landing pages and clean frontend demos before project deadlines.",
    category: "vibe-coding",
    type: "Video",
    url: "https://www.youtube.com/watch?v=djDZHAi75dk",
    youtubeId: "djDZHAi75dk",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/djDZHAi75dk?autoplay=1",
    tags: ["Cursor AI", "Frontend Speed", "Tailwind", "Rapid UI"],
    badge: "UI Speed Build",
    authorOrSource: "Web Design AI",
  },

  // --- 4. PITCHING, DEMOS & JUDGING STRATEGY (YOUTUBE VIDEOS) ---
  {
    id: "judge-pitching-best-practices",
    title: "How to Pitch at Hackathons: Best Practices from an Industry Leading Judge",
    description: "An inside look at how judges score presentations, what common errors turn them off, and how to structure a 2-minute pitch for maximum impact.",
    category: "pitch-prep",
    type: "Video",
    url: "https://www.youtube.com/watch?v=k00WsEPDmrU",
    youtubeId: "k00WsEPDmrU",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/k00WsEPDmrU?autoplay=1",
    tags: ["Judge Advice", "2-Min Pitch", "Scoring Criteria", "Avoid Pitfalls"],
    badge: "Judge Secrets",
    authorOrSource: "Industry Judge Insights",
  },
  {
    id: "presentation-tips-pitch-win",
    title: "Hackathon Presentation Tips to Pitch & Win",
    description: "Practical tips on deck design, slide narrative flow, handling live Q&A sessions under pressure, and presenting incomplete MVPs gracefully.",
    category: "pitch-prep",
    type: "Video",
    url: "https://www.youtube.com/watch?v=ConzkRP2mpk",
    youtubeId: "ConzkRP2mpk",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/ConzkRP2mpk?autoplay=1",
    tags: ["Presentation Deck", "Slide Story", "Q&A Handling", "Winning Pitch"],
    badge: "Pitch Strategy",
    authorOrSource: "Hackathon Winning Plays",
  },

  // --- 5. STRATEGY & MINDSET (YOUTUBE VIDEOS) ---
  {
    id: "win-every-hackathon",
    title: "How to Win EVERY Hackathon (from a Top 50 Hacker)",
    description: "Practical blueprint on scope reduction, picking realistic MVPs, team dynamic split (Design vs. Frontend vs. Pitching), and game-plan execution.",
    category: "beginner-mindset",
    type: "Video",
    url: "https://www.youtube.com/watch?v=JWxcEL4mg_Q",
    youtubeId: "JWxcEL4mg_Q",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/JWxcEL4mg_Q?autoplay=1",
    tags: ["Top 50 Hacker", "MVP Scope", "Team Split", "Pro Strategy"],
    badge: "Pro Blueprint",
    authorOrSource: "Competitive Hacker Spotlight",
  },
  {
    id: "hackathons-explained-beginners",
    title: "Hackathons, Explained for Beginners",
    description: "A concise primer explaining what to expect, how to form teams efficiently, and how first-timers should approach their first competitive event.",
    category: "beginner-mindset",
    type: "Video",
    url: "https://www.youtube.com/watch?v=YyJRXPY0Vyg",
    youtubeId: "YyJRXPY0Vyg",
    youtubeEmbedUrl: "https://www.youtube-nocookie.com/embed/YyJRXPY0Vyg?autoplay=1",
    tags: ["Beginner Guide", "Team Formation", "First Hackathon", "101 Primer"],
    badge: "Beginner 101",
    authorOrSource: "Hacker Foundations",
  },

  // --- 6. SPEED-BUILDING UI & FRONTEND LIBRARIES (WEBSITES - NO THUMBNAIL) ---
  {
    id: "21st-dev",
    title: "21st.dev — AI-Friendly React & Next.js Component Registry",
    description: "AI-friendly component registry built for React and Next.js. Lets you install modular, styled Shadcn/UI components instantly via npx commands.",
    category: "ui-components",
    type: "Website",
    url: "https://21st.dev",
    tags: ["21st.dev", "Shadcn", "Next.js", "AI Components"],
    featured: true,
    badge: "Essential UI",
    authorOrSource: "21st.dev Platform",
  },
  {
    id: "shadcn-ui",
    title: "shadcn/ui — Customizable Component Primitives",
    description: "Accessible, fully customizable UI components copy-pasteable straight into Next.js or React projects with Tailwind CSS.",
    category: "ui-components",
    type: "Website",
    url: "https://ui.shadcn.com",
    tags: ["Shadcn UI", "Tailwind", "Radix UI", "Copy-Paste"],
    authorOrSource: "Shadcn",
  },
  {
    id: "magic-ui",
    title: "Magic UI — Animated Components for High-Converting Landing Pages",
    description: "50+ free and open-source animated components designed for high-converting landing pages and rapid presentation builds.",
    category: "ui-components",
    type: "Website",
    url: "https://magicui.design",
    tags: ["Magic UI", "Animations", "React", "Framer Motion"],
    authorOrSource: "Magic UI",
  },
  {
    id: "aceternity-ui",
    title: "Aceternity UI — Modern Tailwind & Framer Motion Components",
    description: "Ready-to-use Tailwind CSS and Framer Motion components to make your hackathon demo look polished and state-of-the-art.",
    category: "ui-components",
    type: "Website",
    url: "https://ui.aceternity.com",
    tags: ["Aceternity", "Framer Motion", "Tailwind", "Hero Section"],
    authorOrSource: "Manu Arora",
  },

  // --- 7. RAPID BACKEND, DATABASE & AI APIS (TOOLS - NO THUMBNAIL) ---
  {
    id: "supabase",
    title: "Supabase — Instant PostgreSQL Database & Auth",
    description: "Instant PostgreSQL database, authentication, real-time subscriptions, and edge functions with simple SDKs.",
    category: "backend-deploy",
    type: "Tool",
    url: "https://supabase.com",
    tags: ["Postgres", "Auth", "Realtime", "Serverless"],
    authorOrSource: "Supabase Team",
  },
  {
    id: "convex-db",
    title: "Convex / Firebase — Real-Time Data Sync",
    description: "Real-time data synchronization for multi-user collaboration demos and live multi-player hackathon applications.",
    category: "backend-deploy",
    type: "Tool",
    url: "https://convex.dev",
    tags: ["Realtime Sync", "Convex", "Firebase", "WebSockets"],
    authorOrSource: "Convex",
  },
  {
    id: "groq-cloud",
    title: "Groq Cloud — Ultra-Fast LLM Inference API",
    description: "Ultra-fast LLM inference API (500+ tokens/sec) to keep demo latencies near zero during judge reviews.",
    category: "ai-tools",
    type: "Tool",
    url: "https://console.groq.com",
    tags: ["Groq", "Zero Latency", "Llama 3", "Inference"],
    badge: "Speed King",
    authorOrSource: "Groq Inc",
  },
  {
    id: "vercel-ai-sdk",
    title: "Vercel AI SDK — Plug LLMs & Streaming into React",
    description: "Standardized library to plug LLMs, real-time streaming, structured JSON outputs, and tool calls into React & Next.js.",
    category: "ai-tools",
    type: "Tool",
    url: "https://sdk.vercel.ai",
    tags: ["Vercel AI", "LLM Streaming", "Tool Use", "Next.js"],
    authorOrSource: "Vercel Labs",
  },
  {
    id: "ollama",
    title: "Ollama — Run Open-Weight AI Models Locally",
    description: "Run open-weight models (Llama 3, Qwen, DeepSeek) locally to test prompts and logic without spending API credits.",
    category: "ai-tools",
    type: "Tool",
    url: "https://ollama.com",
    tags: ["Local AI", "Ollama", "Zero Cost", "Privacy"],
    authorOrSource: "Ollama Team",
  },

  // --- 8. PITCHING & PRESENTATION TOOLS (GUIDES/TOOLS - NO THUMBNAIL) ---
  {
    id: "5-slide-pitch-method",
    title: "The 5-Slide Pitch Deck Method for Hackathons",
    description: "1. Hook & Problem -> 2. The Solution -> 3. Live Architecture & Demo -> 4. Tech Stack -> 5. Future Roadmap. The exact deck structure used by grand prize winners.",
    category: "pitch-prep",
    type: "Guide",
    url: "https://github.com",
    tags: ["5-Slide Pitch", "Judges Strategy", "Demo Guide"],
    badge: "Winning Blueprint",
    authorOrSource: "Hackathon Mentor Guide",
  },
  {
    id: "gamma-app",
    title: "Gamma.app — AI-Assisted Pitch Deck Generation",
    description: "AI-assisted pitch deck generation to generate polished, beautiful presentation slides 1 hour before final submission.",
    category: "pitch-prep",
    type: "Tool",
    url: "https://gamma.app",
    tags: ["AI Slides", "Gamma", "Pitch Deck", "Emergency Tool"],
    authorOrSource: "Gamma App",
  },
  {
    id: "excalidraw",
    title: "Excalidraw — Hand-Drawn Architecture Diagramming",
    description: "Simple diagramming tool for real-time architecture displays and workflow diagrams during mentor and judge reviews.",
    category: "pitch-prep",
    type: "Tool",
    url: "https://excalidraw.com",
    tags: ["Diagrams", "Architecture", "Excalidraw", "Demo Visuals"],
    authorOrSource: "Excalidraw Open Source",
  },
]
